version: "3"
services:
  identity:
    image: identity
    ports:
      - 3031:3031

  todo:
    image: todo
    environment:
      - USER=$USER
      - AUTH0_DOMAIN=$AUTH0_DOMAIN
      - AUTH0_AUDIENCE=$AUTH0_AUDIENCE
      - TODO_ADDR=$TODO_ADDR
      - TODO_PORT=$TODO_PORT
      - MONGO_URI=$MONGO_URI
    ports:
      - 3030:3030 
    depends_on:
      - mongodb
      - identity
    volumes:
      - ./jwtverifier:/jwtverifier
  
  mongodb:
    image: "mongodb/mongodb-community-server"
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
